name: Lint
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.Js
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        cache: 'npm'
    - run: npm i
    - run: npm run lint
